[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

# Redirect per SPA - escludere file statici
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.js"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.css"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpg"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.jpeg"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.gif"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.svg"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.ico"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.woff"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.woff2"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.ttf"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*.eot"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

# Redirect finale per SPA (solo per route che non corrispondono ai file sopra)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
